DROP DATABASE shelter;
CREATE DATABASE shelter;
USE shelter;

CREATE TABLE shelter_manager (sm_id INT AUTO_INCREMENT PRIMARY KEY , username VARCHAR(20) NOT NULL , password VARCHAR(20) NOT NULL );
CREATE TABLE caretaker (c_id INT AUTO_INCREMENT PRIMARY KEY , name VARCHAR(20) NOT NULL , surname VARCHAR(20) NOT NULL );
CREATE TABLE animal (a_id INT AUTO_INCREMENT PRIMARY KEY , name VARCHAR(20) NOT NULL , age INT NOT NULL , species VARCHAR(20));
CREATE TABLE sponsor (s_id INT AUTO_INCREMENT PRIMARY KEY , name VARCHAR(20) NOT NULL , surname VARCHAR(20) NOT NULL , phone BIGINT NOT NULL );

CREATE TABLE sponsors (s_id INT NOT NULL , a_id INT NOT NULL );
CREATE TABLE responsible_for (c_id INT NOT NULL , a_id INT NOT NULL );

